# Configuration for object detection node
/mjpeg_streamer:
  ros__parameters: 
    # image source topic
    topic: ["/background/color_full", "/background/color_limited", "/background/depth", "/background/depth_limited"]
    topic_sel_word: ["full", "background","depth", "depth_limited" ]
    topic_sel_topic : "/websocket/sel"
    fps_topic: "/websocket/fps"
    # output port
    port: 7777
    print_fps: true
    FPS_STR: "FPS"
    # Use sensor data Quality of Service for messages
    qos_sensor_data: true
    # Message queue size
    qos_history_depth: 5

    
